parameters:
    ezpublish_rest.field_type_processor.ezrichtext.class: eZ\Publish\Core\REST\Common\FieldTypeProcessor\RichTextProcessor

services:
    ezpublish_rest.field_type_processor.ezrichtext:
        class: "%ezpublish_rest.field_type_processor.ezrichtext.class%"
        arguments:
            - "@ezpublish.fieldType.ezrichtext.converter.edit.xhtml5"
        tags:
            - { name: ezpublish_rest.field_type_processor, alias: ezrichtext }
